# Copyright (C) 2013-2014, International Business Machines Corporation. 
# All Rights Reserved.

all: build 

build:
	make -C impl -f Makefile.libftp build

clean:
	make -C impl -f Makefile.libftp clean

